--- disksim-4.0/src/Makefile	2008-05-11 14:30:53.000000000 -0700
+++ src/Makefile	2010-06-09 14:06:57.000000000 -0700
@@ -32,7 +32,7 @@
 
 include .paths
 
-LDFLAGS = -lm -L. -ldisksim $(DISKMODEL_LDFLAGS) $(MEMSMODEL_LDFLAGS) \
+LDFLAGS = -lm -L. -ldisksim $(DISKMODEL_LDFLAGS) $(MEMSMODEL_LDFLAGS)\
                             $(LIBPARAM_LDFLAGS) $(LIBDDBG_LDFLAGS) 
 
 HP_FAST_OFLAGS = +O4
